### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by pnorman** [go-spatial/tegola#481]
When I run `cache seed` with no options I get an index out of range runtime error.
```
$ ~/go/src/github.com/go-spatial/tegola/cmd/tegola/tegola cache seed
2018-08-02 02:21:45 [INFO] config.go:163: loading local config (config.toml)
2018-08-02 02:21:45 [INFO] cache.go:111: zoom list: []
panic: runtime error: index out of range

goroutine 19 [running]:
github.com/go-spatial/tegola/cmd/tegola/cmd.sendTiles(0x0, 0x0, 0x0, 0xc420300120, 0x0, 0x0)
        /home/pnorman/go/src/github.com/go-spatial/tegola/cmd/tegola/cmd/cache.go:358 +0xaee
github.com/go-spatial/tegola/cmd/tegola/cmd.glob..func2.1(0x0, 0x0, 0x0, 0xc420300120)
        /home/pnorman/go/src/github.com/go-spatial/tegola/cmd/tegola/cmd/cache.go:105 +0x4d
created by github.com/go-spatial/tegola/cmd/tegola/cmd.glob..func2
        /home/pnorman/go/src/github.com/go-spatial/tegola/cmd/tegola/cmd/cache.go:104 +0x399
```

**Comment by ARolek** [comment]
@pnorman please pull the latest for v0.7.0. This was already addressed and by default we now set the max zoom to 22 if no max zoom is set.
